import type { LucideIcon } from 'lucide-react';
import {
  Accessibility,
  Activity,
  Anchor,
  Archive,
  AtSign,
  Award,
  BadgeCheck,
  Bell,
  Bike,
  Binary,
  Book,
  Bookmark,
  Bot,
  Braces,
  Briefcase,
  Brush,
  Bug,
  BugOff,
  Building2,
  Cake,
  CalendarClock,
  CalendarDays,
  Camera,
  Car,
  ChartColumn,
  ChartLine,
  ChartPie,
  CircleCheck,
  ClipboardList,
  Clock,
  Cloud,
  Code,
  Coffee,
  Compass,
  Container,
  Cpu,
  CreditCard,
  Crown,
  Database,
  Diamond,
  DollarSign,
  Droplet,
  Eye,
  FileCode,
  FileText,
  Film,
  Flag,
  Flame,
  FlaskConical,
  Folder,
  Frame,
  Gamepad2,
  Gauge,
  Gem,
  Gift,
  GitBranch,
  GitMerge,
  GitPullRequest,
  Globe,
  GraduationCap,
  Hammer,
  HandHelping,
  Handshake,
  HardDrive,
  Headphones,
  Heart,
  HeartHandshake,
  Hourglass,
  Image,
  Inbox,
  Kanban,
  KeyRound,
  Landmark,
  Layers,
  Leaf,
  LifeBuoy,
  Lightbulb,
  ListChecks,
  ListTodo,
  Lock,
  Mail,
  Map,
  MapPin,
  Megaphone,
  MessageCircle,
  MessageSquare,
  Mic,
  Microscope,
  Moon,
  Mountain,
  Music,
  NotebookPen,
  Package,
  Palette,
  Paperclip,
  PartyPopper,
  Pen,
  PenTool,
  Phone,
  Pin,
  Pipette,
  Pizza,
  Plane,
  PlugZap,
  Puzzle,
  Radar,
  Radio,
  Receipt,
  RefreshCw,
  Rocket,
  Route,
  Rss,
  Ruler,
  Scale,
  Scan,
  ScrollText,
  Search,
  Send,
  Server,
  Settings2,
  Shapes,
  Share2,
  Shield,
  ShieldCheck,
  Ship,
  ShoppingCart,
  SlidersHorizontal,
  Smile,
  Snowflake,
  Sparkles,
  Star,
  Sun,
  Tag,
  Target,
  Telescope,
  Terminal,
  TestTube,
  Timer,
  TreePine,
  TrendingUp,
  Trophy,
  Truck,
  UserPlus,
  UserRound,
  Users,
  UsersRound,
  Video,
  Wand,
  Waves,
  Webhook,
  Workflow,
  Wrench,
  Zap,
} from 'lucide-react';
import { cn } from '@/lib/utils';

/**
 * The symbols a team can wear. Keys are what's stored on the team and validated
 * by the API: kebab-case and stable. The first 24 predate this set and keep
 * their names, so teams already using them need no migration.
 *
 * Imported one by one on purpose — `import { icons } from 'lucide-react'` would
 * pull all ~1,500 into the bundle.
 */
export const TEAM_SYMBOLS: Record<string, LucideIcon> = {
  'bug': Bug,
  'tasks': ListChecks,
  'flask': FlaskConical,
  'shield': Shield,
  'rocket': Rocket,
  'pen': Pen,
  'chart': ChartColumn,
  'database': Database,
  'server': Server,
  'book': Book,
  'megaphone': Megaphone,
  'wrench': Wrench,
  'sparkles': Sparkles,
  'people': Users,
  'flag': Flag,
  'zap': Zap,
  'cloud': Cloud,
  'lock': Lock,
  'compass': Compass,
  'package': Package,
  'globe': Globe,
  'headphones': Headphones,
  'milestone': Target,
  'code': Code,
  'git-branch': GitBranch,
  'git-merge': GitMerge,
  'git-pull-request': GitPullRequest,
  'terminal': Terminal,
  'file-code': FileCode,
  'binary': Binary,
  'cpu': Cpu,
  'hard-drive': HardDrive,
  'container': Container,
  'bot': Bot,
  'braces': Braces,
  'shield-check': ShieldCheck,
  'key-round': KeyRound,
  'bug-off': BugOff,
  'test-tube': TestTube,
  'microscope': Microscope,
  'refresh-cw': RefreshCw,
  'workflow': Workflow,
  'webhook': Webhook,
  'plug-zap': PlugZap,
  'palette': Palette,
  'brush': Brush,
  'pipette': Pipette,
  'ruler': Ruler,
  'layers': Layers,
  'frame': Frame,
  'shapes': Shapes,
  'pen-tool': PenTool,
  'image': Image,
  'camera': Camera,
  'film': Film,
  'wand': Wand,
  'clipboard-list': ClipboardList,
  'calendar-days': CalendarDays,
  'list-todo': ListTodo,
  'kanban': Kanban,
  'map': Map,
  'map-pin': MapPin,
  'route': Route,
  'telescope': Telescope,
  'lightbulb': Lightbulb,
  'circle-check': CircleCheck,
  'clock': Clock,
  'hourglass': Hourglass,
  'timer': Timer,
  'calendar-clock': CalendarClock,
  'chart-line': ChartLine,
  'chart-pie': ChartPie,
  'trending-up': TrendingUp,
  'briefcase': Briefcase,
  'building': Building2,
  'credit-card': CreditCard,
  'dollar-sign': DollarSign,
  'shopping-cart': ShoppingCart,
  'receipt': Receipt,
  'handshake': Handshake,
  'badge-check': BadgeCheck,
  'award': Award,
  'trophy': Trophy,
  'message-circle': MessageCircle,
  'message-square': MessageSquare,
  'mail': Mail,
  'send': Send,
  'phone': Phone,
  'video': Video,
  'mic': Mic,
  'bell': Bell,
  'radio': Radio,
  'rss': Rss,
  'at-sign': AtSign,
  'share': Share2,
  'user-round': UserRound,
  'users-round': UsersRound,
  'user-plus': UserPlus,
  'heart-handshake': HeartHandshake,
  'smile': Smile,
  'graduation-cap': GraduationCap,
  'folder': Folder,
  'file-text': FileText,
  'archive': Archive,
  'inbox': Inbox,
  'bookmark': Bookmark,
  'tag': Tag,
  'paperclip': Paperclip,
  'pin': Pin,
  'star': Star,
  'heart': Heart,
  'diamond': Diamond,
  'gem': Gem,
  'crown': Crown,
  'anchor': Anchor,
  'plane': Plane,
  'car': Car,
  'truck': Truck,
  'ship': Ship,
  'bike': Bike,
  'tree-pine': TreePine,
  'leaf': Leaf,
  'flame': Flame,
  'droplet': Droplet,
  'sun': Sun,
  'moon': Moon,
  'snowflake': Snowflake,
  'mountain': Mountain,
  'waves': Waves,
  'coffee': Coffee,
  'pizza': Pizza,
  'cake': Cake,
  'gamepad': Gamepad2,
  'music': Music,
  'puzzle': Puzzle,
  'gift': Gift,
  'party-popper': PartyPopper,
  'hammer': Hammer,
  'settings-2': Settings2,
  'sliders-horizontal': SlidersHorizontal,
  'activity': Activity,
  'gauge': Gauge,
  'radar': Radar,
  'scan': Scan,
  'life-buoy': LifeBuoy,
  'hand-helping': HandHelping,
  'search': Search,
  'eye': Eye,
  'accessibility': Accessibility,
  'scale': Scale,
  'landmark': Landmark,
  'scroll-text': ScrollText,
  'notebook-pen': NotebookPen,
};

export type TeamSymbolName = keyof typeof TEAM_SYMBOLS;

export const TEAM_SYMBOL_NAMES: string[] = Object.keys(TEAM_SYMBOLS);

interface TeamSymbolProps {
  name: string;
  size?: number;
  className?: string;
  /** Any CSS colour. Omitted, the symbol inherits `currentColor`. */
  color?: string;
}

/** A team's symbol, falling back to a neutral mark for an unknown name. */
export function TeamSymbol({ name, size = 16, className, color }: TeamSymbolProps) {
  const Cmp = TEAM_SYMBOLS[name] ?? TEAM_SYMBOLS.tasks;
  return (
    <Cmp
      size={size}
      className={cn('shrink-0', className)}
      style={color ? { color } : undefined}
      aria-hidden
    />
  );
}
