import { AggregateRoot, UniqueEntityID } from '@core/domain';
import { Result } from '@shared/logic/result';
import { Guard } from '@shared/logic/guard';
import { CycleRollup, CycleStatus } from '../enums/cycle.enums';
import { CycleProps } from './cycle.props';

/**
 * One iteration of a team's cycles. On an `auto` team they're generated by the
 * scheduler (`ensureCyclesCurrent`); on a `manual` team the team creates them.
 * Either way the *end* is automatic — the scheduler still freezes stats and
 * rolls unfinished work over — and the status is always derived from the dates,
 * never stored. See features/cycles.md.
 */
export class CycleEntity extends AggregateRoot<CycleProps> {
  private constructor(props: CycleProps, id?: UniqueEntityID) {
    super(props, id);
  }

  static create(
    props: {
      tenantId: string;
      teamId: string;
      number: number;
      name?: string;
      startDate: string;
      endDate: string;
      description?: string | null;
      scopeCount?: number;
      scopePoints?: number;
      completedCount?: number;
      completedPoints?: number;
      unfinishedIds?: string[];
      closedAt?: Date | null;
      createdAt?: Date;
      updatedAt?: Date;
    },
    id?: UniqueEntityID,
  ): Result<CycleEntity> {
    const guard = Guard.againstNullOrUndefinedBulk([
      { argument: props.tenantId, argumentName: 'tenantId' },
      { argument: props.teamId, argumentName: 'teamId' },
      { argument: props.number, argumentName: 'number' },
    ]);
    if (!guard.succeeded) return Result.fail(guard.message);
    if (props.number < 1) return Result.fail('Cycle numbers start at 1');
    if (!props.startDate || !props.endDate) return Result.fail('A cycle needs a date range');
    if (props.endDate < props.startDate) return Result.fail('Cycle end before its start');

    const now = new Date();
    return Result.ok(
      new CycleEntity(
        {
          id: id || new UniqueEntityID(),
          tenantId: props.tenantId,
          teamId: props.teamId,
          number: props.number,
          name: (props.name ?? '').trim(),
          startDate: props.startDate,
          endDate: props.endDate,
          description: props.description ?? null,
          scopeCount: props.scopeCount ?? 0,
          scopePoints: props.scopePoints ?? 0,
          completedCount: props.completedCount ?? 0,
          completedPoints: props.completedPoints ?? 0,
          unfinishedIds: props.unfinishedIds ?? [],
          closedAt: props.closedAt ?? null,
          createdAt: props.createdAt || now,
          updatedAt: props.updatedAt || now,
        },
        id,
      ),
    );
  }

  get id(): UniqueEntityID {
    return this._id;
  }
  get tenantId(): string {
    return this.props.tenantId;
  }
  get teamId(): string {
    return this.props.teamId;
  }
  get number(): number {
    return this.props.number;
  }
  get name(): string {
    return this.props.name;
  }
  get startDate(): string {
    return this.props.startDate;
  }
  get endDate(): string {
    return this.props.endDate;
  }
  get description(): string | null {
    return this.props.description;
  }
  get scopeCount(): number {
    return this.props.scopeCount;
  }
  get scopePoints(): number {
    return this.props.scopePoints;
  }
  get completedCount(): number {
    return this.props.completedCount;
  }
  get completedPoints(): number {
    return this.props.completedPoints;
  }
  get unfinishedIds(): string[] {
    return this.props.unfinishedIds;
  }
  get closedAt(): Date | null {
    return this.props.closedAt;
  }
  get createdAt(): Date {
    return this.props.createdAt;
  }
  get updatedAt(): Date {
    return this.props.updatedAt;
  }

  /** Where this cycle sits relative to `today` (`YYYY-MM-DD`). Dates are the
   *  only authority — a cycle is "completed" the day after it ends even if the
   *  boundary hasn't been processed yet. */
  statusOn(today: string): CycleStatus {
    if (this.props.endDate < today) return CycleStatus.COMPLETED;
    if (this.props.startDate > today) return CycleStatus.UPCOMING;
    return CycleStatus.ACTIVE;
  }

  /** Frozen stats are written exactly once, at boundary processing. */
  get isClosed(): boolean {
    return this.props.closedAt !== null;
  }

  /**
   * Rename and/or re-schedule a manual cycle. Dates move together or not at all
   * — a caller that changes one must pass both, so a half-applied range can't
   * invert the window. Overlap against the team's other cycles is checked by the
   * use-case, which is the only layer that can see them.
   */
  reschedule(next: { name?: string; startDate?: string; endDate?: string }): Result<void> {
    const startDate = next.startDate ?? this.props.startDate;
    const endDate = next.endDate ?? this.props.endDate;
    if (endDate < startDate) return Result.fail('Cycle end before its start');

    if (next.name !== undefined) this.props.name = next.name.trim();
    this.props.startDate = startDate;
    this.props.endDate = endDate;
    this.props.updatedAt = new Date();
    return Result.ok();
  }

  /** Set (or clear) the cycle's goal/notes. Trims; an empty string clears it to
   *  `null`, so "" and whitespace never persist as a non-empty description. */
  setDescription(text: string | null): void {
    const trimmed = (text ?? '').trim();
    this.props.description = trimmed.length ? trimmed : null;
    this.props.updatedAt = new Date();
  }

  /** Freeze the stats AND who was unfinished — the record of "planned here but
   *  not done" the sweep is about to erase from the issues themselves. */
  close(rollup: CycleRollup, at: Date = new Date()): void {
    this.props.scopeCount = rollup.scopeCount;
    this.props.scopePoints = rollup.scopePoints;
    this.props.completedCount = rollup.completedCount;
    this.props.completedPoints = rollup.completedPoints;
    this.props.unfinishedIds = rollup.unfinishedIds;
    this.props.closedAt = at;
    this.props.updatedAt = at;
  }
}
